# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ferran Pujol Camins
email: me@ferranpujolcamins.cat
description: >- # this means to ignore newlines until "baseurl:"
  I'm a versatile software developer with a mathematics background who has developed his professional career as an iOS developer.
  I'm now looking for new professional challenges as a C++ developer. I'm comfortable solving new problems and learning new things.
  I've contributed to several open source projects in different languages.
  I know C++, Rust and Swift, among other languages.
  My skills include mathematics, algorithmics, functional programming, category theory and basic electronics.
   
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ferranpujolcamins.cat" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ferranpujolca
github_username:  ferranpujolcamins

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-diagrams

liquid:
  error_mode: strict

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
