name: Publish

on:
  push:
    branches: [ swift ]

jobs:
  buildAndPublish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1.3.0
      - name: Generate
        run: swift run
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: github-pages
          FOLDER: build
          CLEAN: true
